### ISSUE TITLE
谈谈一些有趣的CSS题目

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#1]
开本 `issues` ，讨论一些有趣的 CSS 题目，抛开实用性而言，一些题目为了拓宽一下解决问题的思路，此外，涉及一些容易忽视的 CSS 细节。

### 1、下面这个图形，只使用一个标签，可以有多少种实现方式：

![border](http://images.cnblogs.com/cnblogs_com/coco1s/881614/o_border.png)

假设我们的单标签是一个 `div`:
```html
<div></div>
```
定义如下通用`CSS`：
```css
div{
	position:relative;
	width:200px;
	height:60px;
	background:#ddd;
}
```
##### 法一：border
这个应该是最最最容易想到的了
```css
div{
	border-left:5px solid deeppink;
}
```
##### 法二：使用伪元素
一个标签，算上 `before` 与 `after` 伪元素，其实算是有三个标签，这也是很多单标签作图的基础，本题中，使用伪元素可以轻易完成。
```css
div::after{
	content:"";
	width:5px;
	height:60px;
	position:absolute;
	top:0;
	left:0;
	background:deeppink;
}
```
##### 法三：外 box-shadow
盒阴影 `box-shadow` 大部分人都只是用了生成阴影，其实阴影可以有多重阴影，阴影不可以不虚化，这就需要去了解一些 `box-shaodw` 的每一个参数具体作用。使用 `box-shaodw` 解题：
```css
div{
	box-shadow:-5px 0px 0 0 deeppink;
}
```
##### 法四：内 box-shadow
盒阴影还有一个参数 `inset` ，用于设置内阴影，也可以完成：
```css
div{
	box-shadow:inset 5px 0px 0 0 deeppink;
}
```
##### 法五：drop-shadow
`drop-shadow` 是 CSS3 新增滤镜 `filter` 中的其中一个滤镜，也可以生成阴影，不过它的数值参数个数只有 3 个，比之 box-shadow 少一个。
```css
div{
    filter:drop-shadow(-5px 0 0 deeppink);
}
```
##### 法六：渐变 linearGradient
灵活使用 CSS3 的渐变可以完成大量想不到的图形，CSS3 的渐变分为线性渐变和径向渐变，本题使用线性渐变，可以轻易解题：
```css
div{
	background-image:linear-gradient(90deg, deeppink 0px, deeppink 5px, transparent 5px);
}
```
##### 法七：轮廓 outline
这个用的比较少，outline （轮廓）是绘制于元素周围的一条线，位于边框边缘的外围，可起到突出元素的作用。这个方法算是下下之选。
```css
div{
	height:50px;
	outline:5px solid deeppink;
}
div{
	position:absolute;
	content:"";
	top:-5px;
	bottom:-5px;
	right:-5px;
	left:0;
	background:#ddd;
}
```
上述就是我想到的 7 种方法，不排除有没想到的，具体实现可以戳这里看看：

[codepen-单标签左边竖条的实现方式  ](https://codepen.io/Chokcoco/pen/PGkgRX)

**Comment by idiotWu** [comment]
`background-image` 默认也是从 `border-box` 延展开的：

![2016-09-19 19 40 22](https://cloud.githubusercontent.com/assets/6022672/18629527/0e8ffd20-7ea1-11e6-8b1a-8a7cb16fbc69.png)

**Comment by wangpengfei15975** [comment]
+1

**Comment by chokcoco** [comment]
@idiotWu
你这个是 solid 哦，你把solid换成 dashed看看，
我上面的题目写到一半吃饭去了，还没写完，我写了一个demo也可以看看
https://codepen.io/Chokcoco/pen/QKyZPb

**Comment by chokcoco** [comment]
@idiotWu 
刚刚没看清楚就瞎回复了，见谅。
看你图中的确实是从 border 开始的，有demo吗，我这边的demo都是从
paading-box 开始的。
[CssBackground](https://codepen.io/Chokcoco/pen/QKyZPb)

**Comment by idiotWu** [comment]
查了相关的标准，发现原因在于你设定了 `background-repeat: no-repeat`。

background image 的绘制中有两个因素决定了绘图区域：

1. [background positioning area](https://drafts.csswg.org/css-backgrounds-3/#background-positioning-area)。`background-origin` 属性决定了这个**相对定位位置**，默认为 `padding-box`。所以默认的背景图片绘制是从 padding box 的左上顶点开始的。

2. [background painting area](https://drafts.csswg.org/css-backgrounds-3/#background-painting-area)。`background-clip` 属性决定了**绘制区间**，默认为 `border-box`。所以在 `background-repeat: repeat` 的情况下：

> The image is repeated in this direction as often as needed to cover the background painting area.

**Comment by chokcoco** [comment]
@idiotWu 
感谢提出，我正好也在查看标准是怎么定义的，我补充到题中去。

**Comment by wangpengfei15975** [comment]
嗯 吹毛求疵一下。
第四题的法2为什么不直接用rotateX = =

**Comment by chokcoco** [comment]
@wangpengfei15975 
厉害了我的哥，两个写法确实是一样的，rotateX 应该是更简洁的。

**Comment by zhanhongtao** [comment]
第五个, 已经用了 flex box, 可以直接在侧轴方向上居中. [DEMO](http://codepen.io/redky/full/gwkqXQ/)

**Comment by Serena211** [comment]
sorry, 刚刚发错地方了。第二个dashed border box 的outline解法

.style_outline {
    &::before{
      content:"";
      position:absolute;
      top:0;
      left:0;
      bottom:0;
      right:0;
      outline:20px solid #ffc107;
      background:#fff;
      z-index:-1;
}
感觉这样更合理一点。

**Comment by Mmzer** [comment]
非常有意思

**Comment by jiangxiaolin1995** [comment]
啊哈，脑洞好大啊

**Comment by OnionStu** [comment]
第5题，如果加上点击加载更多呢…要如何实现？

**Comment by github302** [comment]
第1题，当用border-left设置样式的时候，div的整个宽度就会加长，如果想要div整体宽度不变的话，就需要加上box-sizing:border-box; 
使用外 box-shadow的时候div宽度也会加长，内 box-shadow就不会，所以如果需求还要保证div整体宽度不变的话，得注意下这些点。

`.demo1 {
	position:relative;
	width:200px;
	height:60px;
	background:#ddd;
}

.demo2 {
	position:relative;
	width:200px;
	height:60px;
	background:#ddd;
}

.demo2:after {
	position:absolute;
	left:0;
	top:0;
	content:'';
	width:5px;
	height:60px;
	background: deeppink;
}

.demo3 {
	position:relative;
	width:200px;
	height:60px;
	background:#ddd;
	box-shadow: inset 5px 0 0 deeppink;
}

.demo4 {
	position:relative;
	width:200px;
	height:60px;
	background:#ddd;
	border-left:solid 5px deeppink;
	box-sizing:border-box;
}
.demo5 {
	position:relative;
	width:200px;
	height:60px;
	background:#ddd;
	box-shadow:-5px 0 0 deeppink;
}
.demo6 {
	position:relative;
	width:200px;
	height:60px;
	background:#ddd;
	border-left:solid 5px deeppink;
}
<div class="demo1"></div>
<br/>
<div class="demo2"></div>
<br/>
<div class="demo3"></div>
<br/>
<div class="demo4"></div>
<br/>
<div class="demo5"></div>
<br/>
<div class="demo6"></div>
<br/>`
可以对比看下容器宽度

**Comment by olovey** [comment]
好厉害啊，刚入前端，真的学习到很多。谢谢

**Comment by chokcoco** [comment]
@olovey 
建议去我的博客读这些文章，可以看到Demo，效果更好，github没办法嵌入iframe。

**Comment by desperadoray** [comment]
1. 法3  [code] box-shaodw -> shadow

**Comment by wmh1106** [comment]
第四题：如果是倒影，还可以用缩放来做的scale
[demo](http://js.jirengu.com/bidebipisa/4/edit)

**Comment by jokum** [comment]
第一个：不知道用背景图片(repeat-y)算不算

**Comment by llqkl** [comment]
专门注册了来问一下，为什么第二题的法一，我得到的结果是这样的呢，边框从左上角开始，但是是连着的，不是左上角一个小方块那种
![qq 20180515104238](https://user-images.githubusercontent.com/39287714/40033879-e749f344-582c-11e8-929f-6a344c91a01c.jpg)

**Comment by yanchuan1990** [comment]
it is good for everyone.

**Comment by huan-joy** [comment]
关于前两个问题，其实还可以直接用<img>标签嘛（要是说不能包含外部图片，可以把图片转成base64编码嘛），同理还可以使用<svg>标签嘛。

**Comment by zsjun** [comment]
![image](https://user-images.githubusercontent.com/8063904/46726033-0a110c80-ccb0-11e8-9f1c-d4d2243ca685.png)


> 专门注册了来问一下，为什么第二题的法一，我得到的结果是这样的呢，边框从左上角开始，但是是连着的，不是左上角一个小方块那种
> ![qq 20180515104238](https://user-images.githubusercontent.com/39287714/40033879-e749f344-582c-11e8-929f-6a344c91a01c.jpg)
我的也是，感觉是lz写法有问题

**Comment by chokcoco** [comment]
@zsjun 我尝试了下现版本的chrome下确实是上图你发的效果。
因为写这个这篇文章的时间距离现在有一段时间了，我再去确认考究下，再给你个答复~

**Comment by mask2012** [comment]
> 关于移动端多行省略 我这里有个更好的实现
> https://codepen.io/isjemair/pen/oMRZvm
> 切换最外层的folded类名就可以实现查看更多和收起状态
> 
> 法一的实现不能实现点击查看更多
> 法二的实现很容易造成文字被截一半
> 
> 原本的方法是在网上找到一个老外的 我在做的时候是把其中的参数抽出来作为变量

@Jemair 你的demo的问题是展开是用颜色盖在上边的，所以底部背景变化，或不是纯色会露出马脚
![image](https://user-images.githubusercontent.com/6481461/46846003-7a36a400-ce10-11e8-9508-bf390a06702a.png)

**Comment by bloggerwjk** [comment]
父元素 display: flex;flex-direction: row-reverse;  子元素margin-left:负值   好像也行

**Comment by wd2010** [comment]
大神你好,这些思考非常值得学习。关于第2道思考题我在backgroun-image和background-color上有点疑惑想请教下。下图是我通过伪元素实现的，但我想通过background-image的多背景实现，内部的background-image的终止点总是在border右下角，我想把它终止点在padding右下角，请问可以怎么实现呢？
![1111111111](https://user-images.githubusercontent.com/16284915/48237434-873fb680-e401-11e8-97df-367e988cc739.png)


以下是我想实现的代码，但不起作用
```css
div{
      margin:20px;
      width: 400px;
      height:400px;
      border: 10px dashed green;
      padding: 20px;
      background-repeat: no-repeat;
      background-image:
          url(./img/1.jpg),
          linear-gradient(to right, red,red);
      background-clip: padding-box, border-box;
    }
```
