### ISSUE TITLE
CSS 文字装饰 text-decoration & text-emphasis

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#103]
本文未完成

-----

在 CSS 中，文字算是我们天天会打交道的一大类了。本文将讲讲比较新的两个文字装饰的概念 `text-decoration` 与 `text-emphasis`。

## text-emphasis

`text-emphasis` 意为文字强调，是 [CSS Text Decoration Module Level 3](https://drafts.csswg.org/css-text-decor-3/#text-emphasis-property) 才新增的一个属性，用于增强文字强调的效果。

在早些时候，我们如果要强调几个字，可能更多是使用**加粗**，**斜体**这种较为常规的文字样式类型：

```CSS
{
    font-weight: bold;   // 加粗
    font-style: italic;  // 斜体
}
```
