### ISSUE TITLE
巧用滤镜实现带高级融合感的文字快闪切换效果

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#149]
本文未完成

-----

今天偶然看到这样一类很有意思的**文字快闪动画**：

![](https://user-images.githubusercontent.com/8554143/140744218-b6cbb5e0-05a1-4658-8d9c-bca6c5dd15ff.gif)

这类文字快闪切换效果运用得当的话，能比较好的吸引用户的眼球。

当然，今天并非是想用 CSS 实现上述的的效果。在尝试的过程中，我发现了另外一类能够使用 CSS 非常轻松实现**文字快闪动画**，运用了`blur()` 滤镜和 `contrast()` 滤镜产生的融合效果，类似于这样：

![](https://user-images.githubusercontent.com/8554143/140744814-93cafebb-47a1-4224-a6f0-356669b4807e.gif)

这个技巧也在多篇文章就提及，本文再简述下。

## blur 滤镜混合 contrast 滤镜产生融合效果

本文的重点，**模糊滤镜叠加对比度滤镜产生的融合效果**。单独将两个滤镜拿出来，它们的作用分别是：

1. `filter: blur()`： 给图像设置高斯模糊效果。
2. `filter: contrast()`： 调整图像的对比度。

但是，当他们“合体”的时候，产生了奇妙的融合现象。

先来看一个简单的例子：

![](https://user-images.githubusercontent.com/8554143/30364156-9b5dc8e0-9895-11e7-876e-4c43af234ca3.gif)

[CodePen Demo -- filter mix between blur and contrast](https://codepen.io/Chokcoco/pen/QqWBqV)

仔细看两圆相交的过程，在边与边接触的时候，会产生一种边界融合的效果，通过对比度滤镜把高斯模糊的模糊边缘给干掉，利用高斯模糊实现融合效果。

上述效果的实现基于两点：

1. 图形是在被设置了 `filter: contrast()` 的画布背景上进行动画的
2. 进行动画的图形被设置了 `filter: blur()`（ 进行动画的图形的父元素需要是被设置了 `filter: contrast()` 的画布）

当然，背景色不一定是白色，我们稍稍修改上面的Demo，简单的示意图如下：

![](https://user-images.githubusercontent.com/8554143/30364469-f3347b58-9896-11e7-82ec-ee7b32189a1a.png)

## 使用 blur/contrast 滤镜实现文字的切换

利用上述的技巧，我们可以实现文字的融合效果，像是这样：

![](https://user-images.githubusercontent.com/8554143/30375460-317c7cf2-98bb-11e7-8659-c764c20f07bb.gif)

这样，利用这个技巧，我们可以巧妙构思一下动画：

1. 多个文字按顺序依次出现（利用 `animation-delay` 进行控制处理）
2. 做到上一个文字消失的同时，下一个文字出现
3. 叠加上上述的滤镜即可

核心代码如下：

```HTML
<div class="g-container">
  <div class="word">iPhone</div>
  <div class="word">13</div>
  <div class="word">Pro</div>
  <div class="word">强得很！</div>
</div>
```
```CSS
@import url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');

$speed: 8s;
$wordCount: 4;

.g-container {
    position: relative;
    width: 100vw;
    height: 100vh;
    background: #000;
    font-family: 'Montserrat', sans-serif;
    color: #fff;
    font-size: 120px;
    filter: contrast(15);
}
.word {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    animation: change $speed infinite ease-in-out;

    @for $i from 0 to $wordCount {
        &:nth-child(#{$i + 1}) {
            animation-delay: ($speed / ($wordCount + 1) * $i) - $speed;
        }
    }
}

@keyframes change {
    0%,
    5%,
    100% {
        filter: blur(0px);
        opacity: 1;
    }
    50%,
    80% {
        filter: blur(80px);
        opacity: 0;
    }
}
```
