### ISSUE TITLE
巧妙实现内凹的平滑圆角

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#154]
## 背景

某日，群友们在群里抛出这样一个问题，如何使用 CSS 实现如下的布局：

![](https://user-images.githubusercontent.com/8554143/144418823-9a7aa37b-def0-4311-985c-462b24cdec38.png)

在 CSS 世界中，如果只是下述这种效果，还是非常容易实现的：

![](https://user-images.githubusercontent.com/8554143/144419034-e78915b5-4778-40c7-a690-1b67891aba64.png)

一旦涉及到圆角或者波浪效果，难度就会提升很多。

实现这种连续平滑的曲线其实是比较麻烦的，当然，也不是完全没有办法。本文，就会带大家看看，使用 CSS 实现上述内凹平滑圆角效果的一些可能的方式。

## 利用圆的衔接实现

第一种方法比较笨。我们可以使用多个圆的衔接实现。

首先，我们会实现一个内部挖出一个矩形的矩形：

```HTML
<div></div>
```

核心 CSS 代码如下：

```CSS
div {
    height: 200px;
    background: 
        linear-gradient(90deg, #9c27b0, #9c27b0 110px, transparent 110px, transparent 190px, #9c27b0 190px),
        linear-gradient(90deg, #9c27b0, #9c27b0);
    background-size: 100% 20px, 100% 100%;
    background-position: 0 0, 0 20px;
    background-repeat: no-repeat;
}
```

得到这样一个图形（实现的方式有很多，这里我利用的是渐变）：

![](https://user-images.githubusercontent.com/8554143/144419735-4743e8fd-7570-4a76-99e8-2178302f1ad6.png)

接下来，就是通过伪元素去叠加三个圆，大概是这样：

![](https://user-images.githubusercontent.com/8554143/144420217-44f25979-6157-4aed-9a4b-71315d7f0ee5.png)

```CSS
div {
    ...
    &::before {
        position: absolute;
        content: "";
        width: 40px;
        height: 40px;
        border-radius: 50%;
        background: #000;
        left: 90px;
        box-shadow: 40px 0 0 #000, 80px 0 0 #000;
    }
}
```

稍微，修改一下三个圆的颜色，我们就可以得到如下的效果：

![](https://user-images.githubusercontent.com/8554143/144420454-5f736ca0-c8a7-4af7-9f1b-391cf59b0810.png)

可以看到，这种通过 3 个圆的叠加实现的效果并不是太好，只能说是勉强还原，如果背景色不是纯色，就穿帮了：

![](https://user-images.githubusercontent.com/8554143/144420679-f35c111f-2550-4c7d-935a-a2d991594bd7.png)

完整的代码你可以戳这里：[CodePen Demo - Smooth concave rounded corners](https://codepen.io/Chokcoco/pen/oNGgyeK)
