### ISSUE TITLE
Amazing！！CSS 也能实现烟雾效果？

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#156]
本文未完成

----

最近利用 CSS 实现了一些看似超出 CSS 能力的效果：

+ [巧用渐变实现高级感拉满的背景光动画](https://github.com/chokcoco/iCSS/issues/150)
+ [Amazing！！CSS 也能实现极光？](https://github.com/chokcoco/iCSS/issues/155)

本文继续此系列，本文主要想探讨一下，使用 CSS 能否比较好的实现一些**烟雾效果**。像是这样：

![](https://user-images.githubusercontent.com/8554143/147092625-87c88cc2-d99f-49cc-9658-e8f739d3ea67.png)

仔细观察烟雾效果，有两个比较重要的特点：

+ 模糊效果
+ 颗粒感

首先看模糊效果，想到模糊，大部分同学首先都会想到使用 `filter: blur()` 。当然没错，不过在 CSS 中，我们还能使用一类其他手段去模拟**模糊**的效果。

我们首先来看这样一个效果：

![](https://user-images.githubusercontent.com/8554143/147093514-426ab79c-ba3b-43f9-8f14-7e3a19946735.gif)

假设，我们有这样一个字符：

```HTML
<span>C</span>
```

我们仅仅是通过 `text-shadow` + `opacity` 的变化，就能模拟烟雾的效果：

```CSS
span {
  text-shadow: 0 0 0 whitesmoke;
  animation: smoky 5s;
}

@keyframes smoky {
  to {
    text-shadow: 0 0 20px whitesmoke;
    opacity: 0;
  }
}
```

看看效果：

![](https://user-images.githubusercontent.com/8554143/147094578-0eeff445-7bf0-4874-9576-2c0a5c8880db.gif)

在上述的基础上，我们可以加上位移、旋转、缩放，稍微改造一下上述代码，添加一些 `transform` 变换：

```CSS
span {
  text-shadow: 0 0 0 whitesmoke;
  animation: smoky 5s;
}

@keyframes smoky {
  to {
    transform:
      translate3d(200px, -80px, 0)
      rotate(-40deg)
      skewX(70deg)
      scale(1.5);
    text-shadow: 0 0 20px whitesmoke;
    opacity: 0;
  }
}
```

就可以得到如下效果：

![](https://user-images.githubusercontent.com/8554143/147095187-30d05098-3855-4277-bc39-d0f57c0cac47.gif)

叠加了 `transform` 之后，就很有一个字被吹跑，变成烟雾的感觉。在此基础之上，我们只需要将多个字放在一起，利用 `animation-delay` 顺序控制每个字触发动画效果，即可得到上述的完整烟雾效果。

伪代码如下：

```HTML
<div>
    <span>C</span>
    <span>S</span>
    <span>S</span>
    // ...
</div>
```
```CSS
// ... 上述所有 CSS 代码

@for $item from 1 through 21 {
  span:nth-of-type(#{$item}){ 
    animation-delay: #{(($item/10))}s; 
  }
} 
```

就可以得到这样一个被风吹跑的字，幻化成烟雾的效果：

![](https://user-images.githubusercontent.com/8554143/147093514-426ab79c-ba3b-43f9-8f14-7e3a19946735.gif)
