### ISSUE TITLE
巧用 CSS 视差实现酷炫交互动效

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#178]
本文未完成

----

本文将介绍利用 CSS 实现滚动视差效果的一个小技巧，并且，利用这个技巧来制作一些有意思的交互特效。

关于使用 CSS 实现滚动视差效果，在之前有一篇文章详细描述过具体方案 - [CSS 实现视差效果](https://github.com/chokcoco/iCSS/issues/37)，感兴趣的同学可以先看看这篇文章。

这里，会运用上这样一种纯 CSS 的视差技巧：

## 使用 `transform: translate3d` 实现滚动视差

这里利用的是 CSS 3D，实现滚动视差效果。

原理就是：

1. 我们给容器设置上 `transform-style: preserve-3d` 和 `perspective: xpx`，那么处于这个容器的子元素就将位于3D空间中，

2. 再给子元素设置不同的 `transform: translateZ()`，这个时候，不同元素在 3D Z轴方向距离屏幕（我们的眼睛）的距离也就不一样

3. 滚动滚动条，由于子元素设置了不同的 `transform: translateZ()`，那么他们滚动的上下距离 `translateY` 相对屏幕（我们的眼睛），也是不一样的，这就达到了滚动视差的效果。

> 关于 `transform-style: preserve-3d` 以及 `perspective` 本文不做过多篇幅展开，默认读者都有所了解，还不是特别清楚的，可以先了解下 CSS 3D。

核心代码表示就是：

```HTML
<div class="g-container">
    <div class="section-one">translateZ(-1)</div>
    <div class="section-two">translateZ(-2)</div>
    <div class="section-three">translateZ(-3)</div>
</div>
```

```CSS
html {
    height: 100%;
    overflow: hidden;
}

body {
    perspective: 1px;
    transform-style: preserve-3d;
    height: 100%;
    overflow-y: scroll;
    overflow-x: hidden;
}

.g-container {
    height: 150%;

    .section-one {
        transform: translateZ(-1px);
    }
    .section-two {
        transform: translateZ(-2px);
    }
    .section-three {
        transform: translateZ(-3px);
    }
}

```

总结就是父元素设置 `transform-style: preserve-3d` 和 `perspective: 1px`，子元素设置不同的 `transform: translateZ`，滚动滚动条，效果如下：

![css3dparallax](https://user-images.githubusercontent.com/8554143/43886275-cba87da4-9bed-11e8-9217-67be497879ae.gif)

[CodePen Demo -- CSS 3D parallax](https://codepen.io/Chokcoco/pen/EpOeRm)

很明显，当滚动滚动条时，不同子元素的位移程度从视觉上看是不一样的，也就达到了所谓的滚动视差效果。
