### ISSUE TITLE
新时代布局新特性 -- 容器查询

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#201]
终于，在漫长的等待下，容器查询（CSS Container Queries）将在 Chrome 105 版本得到正式的支持！

![image](https://user-images.githubusercontent.com/8554143/186660236-010767e2-8096-42be-b663-d01715bf7f62.png)

而目前，我们也能在 Chrome Canary 版本中，或者在 Chrome 93~104 通过开启 `Enable CSS Container Queries` 特性抢先体验。

## 响应式过往的痛点

在之前，响应式有这么个掣肘。同一 DOM 的不同布局形态如果想要变化，需要依赖诸如**媒体查询**来实现。

像是这样：

![](https://user-images.githubusercontent.com/8554143/186666296-054ce41c-672c-40c2-a285-d6560b990f41.gif)

通过浏览器视窗大小的变化，借助媒体查询，实现不一样的布局。

但是，在现如今，大部分 PC 端页面使用的是基于 Flex/Grid 的弹性布局。

很多时候，当内容数不确定的时候，即便是相同的浏览器视窗宽度下，元素的布局及宽度可能也是不一致的。

考虑下面这种情况：

```HTML
<!-- 情况一  -->
<ul class="wrap">
    <li></li>
    <li></li>
    <li></li>
</ul>
<!-- 情况二  -->
<ul class="wrap">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
</ul>
```
```CSS

.wrap {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
}
li {
    width: 190px;
    height: 100px;
    flex-grow: 1;
    flex-shrink: 0;
}
```
![](https://user-images.githubusercontent.com/8554143/186668221-53f7b868-e326-4fbe-b217-588304378117.png)

这种情况下，如果需要在不同宽度下对最后一个元素做一下处理，传统方式还是比较麻烦的。

在这种情况下，容器查询（CSS Container Queries）就应运而生了！

它给予了 CSS，在不改变浏览器视口宽度的前提下，只是根据容器的宽度变化，对布局做成调整的能力。

像是这样。
