### ISSUE TITLE
有趣的六芒星能力图动画

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#228]
最近，在看 LPL 比赛的时候，看到这样一个有意思的六芒星能力图动画：

今天，我们就来使用纯 CSS 实现这样一个动画效果！ 

## 实现背景网格

对于如下这样一个背景网格，**最好的方式当然肯定是切图**。

![](https://user-images.githubusercontent.com/8554143/226373559-f1e3912d-a09b-4aa3-b99b-4480c2be9fa9.png)

如果一定要使用 CSS，勉强也能做，这就涉及了**不规则图形边框**效果，我们有一些方式可以实现，可以参考一下这几篇文章：

+ [现代 CSS 高阶技巧，不规则边框解决方案](https://github.com/chokcoco/iCSS/issues/221)
+ [有意思！不规则边框的生成方案](https://github.com/chokcoco/iCSS/issues/106)

这里，我们可以使用 `drop-shadow()`，大致实现一下这个效果，核心步骤：

1. 通过叠加实现一个六边形图形
2. 利用 `drop-shadow()` 实现边框效果

用动图演示一下，大概是这样：

![](https://user-images.githubusercontent.com/8554143/226378686-1d3dd180-3bc2-46c3-a1d7-b13138f01f83.gif)

代码如下：

```HTML
<div></div>
```
```CSS
div {
    width: 150px;
    height: 260px;
    background: #fff;
    filter: 
        drop-shadow(0 0 .5px #333)
        drop-shadow(0 0 .5px #333)
        drop-shadow(0 0 .5px #333);
    &::before,
    &::after {
        content: "";
        position: absolute;
        inset: 0;
        background: inherit;
    }
    &::before {
        transform: rotate(60deg);
    }
    &::after {
        transform: rotate(-60deg);
    }
}
```

效果如下：

![](https://user-images.githubusercontent.com/8554143/226379801-4732ae5a-4e46-405a-9186-7078843558fa.png)
