### ISSUE TITLE
带圆角的虚线边框？CSS 不在话下

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#250]
今天，我们来看这么一个非常常见的切图场景，我们需要一个带圆角的虚线边框，像是这样：

![](https://github.com/chokcoco/iCSS/assets/8554143/559cb844-01fe-46f1-bd7b-c7cb00db4f03)

这个我们使用 CSS 还是可以轻松解决的，代码也很简单，核心代码：

```CSS
div {
    border-radius: 25px;
    border: 2px dashed #aaa;
}
```

但是，原生的 `dashed` 有一个问题，就是我们**无法控制虚线的单段长度与间隙**。

假设，我们要这么一个效果呢虚线效果呢：

![](https://github.com/chokcoco/iCSS/assets/8554143/198b0707-085a-4c55-beac-046e5dc0be27)

此时，由于无法控制 `border: 2px dashed #aaa` 产生的虚线的单段长度与线段之间的间隙，border 方案就不再适用了。

那么，在 CSS 中，我们还有其它方式能够实现带圆角，且虚线的单段长度与线段之间间隙可控的方式吗？

本文，我们就一起探讨探讨。

## 实现不带圆角的虚线效果

上面的场景，使用 CSS 实现起来比较麻烦的地方在于，图形有一个 `border-radius`。

如果不带圆角，我们可以使用**渐变**，很容易的模拟虚线效果。

我们可以使用**线性渐变**，轻松的模拟虚线的效果：

```CSS
div {
    width: 150px;
    height: 100px;
    background: linear-gradient(90deg, #333 50%, transparent 0) repeat-x;
    background-size: 4px 1px;
    background-position: 0 0;
}
```

看看，使用渐变模拟的虚线如下：

![
](https://github.com/chokcoco/iCSS/assets/8554143/62cab4f7-f5d9-47b1-988d-92069e1c7f97)

解释一下上面的代码：
1. linear-gradient(90deg, #333 50%, transparent 0)，实现一段渐变内容，100% - 50% 的内容是 #333 颜色，剩下的一半 50% - 0 的颜色是透明色 transprent
2. repeat-x 表示只在 x 方向重复
3. background-size: 4px 1px 表示上述渐变内容的长宽分别是 4px\ 1px，这样配合 repeat-x就能实现只有 X 方向的重复
4. 最后的 background-position: 0 0 控制渐变的定位

因此，我们只需要修改 `background` 的参数，就可以得到各种不一样的虚线效果：

![](https://github.com/chokcoco/iCSS/assets/8554143/36bcacb3-7e6b-4aee-9f58-33f6e682a545)

完整的代码，你可以戳这里：[CodePen Demo -- Linear-gradient Dashed Effect](https://codepen.io/Chokcoco/pen/zYeXKaO)
