### ISSUE TITLE
渐变边框字体？CSS 轻松拿捏！

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#264]
今天，有个群友问了我这么一个问题，如果不想切图，是否有办法实现带渐变边框的字体效果？如下所示：

![](https://github.com/chokcoco/iCSS/assets/8554143/140bc6b7-c343-4355-82e1-fbe360b7f493)

本文，就将带尝试一下，在 CSS 中，我们可以如何尽可能的实现这种渐变边框字体效果。

## 元素叠加

首先，比较容易想到的写法是通过元素叠加实现。

1. 元素本身实现文字效果本身
2. 通过元素的伪元素，配合 `background-clip: text` 实现渐变文字，并且通过 transform 或者设置大几号的文字，实现渐变字体
3. 将（1）（2）进行叠加

我们尝试一下这种方式：

```HTML
<div data-text="4"></div>
```
```CSS
div {
    position: relative;
    width: 300px;
    height: 150px;
    font-size: 100px;
    text-align: center;
    font-weight: bold;

    &::before,
    &::after {
        content: attr(data-text);
        position: absolute;
        inset: 0;
        color: #000;
    }
    
    &::before {
        transform: scale(1.1);
        background: linear-gradient(cyan, #fc0);
        background-clip: text;
        color: transparent;
    }
}

```

这里，我们让 `before 伪元素` 和 `after 伪元素` 两个伪元素进行具体内容的展示，`after 伪元素` 只展示具体的文字，字号为 `100px`，而`before 伪元素`放大一点点后叠加在另外一个伪元素下面，效果如下：

![](https://github.com/chokcoco/iCSS/assets/8554143/eed347ad-6957-4cb0-a584-dafc29c35e35)

可以看到，这种方式，边框并不均匀。

而且，如果字数更多，效果更差：

![](https://github.com/chokcoco/iCSS/assets/8554143/6c6e336e-f3b6-4191-b666-b9ccfd271522)

所以，通过叠加实现，显然不可取。
