### ISSUE TITLE
多种方式实现单侧阴影

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#265]
最近，在几个不同的群里都遇到有人在问同一个问题，如何使用 CSS 实现如下所示的单侧阴影：

![](https://github.com/chokcoco/iCSS/assets/8554143/fe6e93e4-578d-491e-83d7-883c142bbd2d)

也就是正常而言，阴影应该是出现在多条边上的，而现在，我们只希望阴影固定只能出现在某一侧。

单侧阴影其实是一个非常老生常谈的话题，在 CSS 中之前也有比较巧妙的方式实现。当然，CSS 发展到今天，我们有了更多种不同方式来实现单侧阴影这个需求，本文我们就一起来看看。

## 方法一：overflow: hidden

这个应该是最容易想到的方式了，其思路也非常好理解：

1. 选定我们需要阴影的那一侧
2. 另外三侧通过叠加一个容器，通过 overflow: hidden 解决

什么意思呢？通过下面这张示意图，一看就懂：

![](https://github.com/chokcoco/iCSS/assets/8554143/b9a2e37d-a0bd-44a9-a7ca-4de096d3cb71)

这样，利用父容器 `overflow: hidden` 的特性，我们将实际容器的 3 条边与父容器重叠，另外一侧留出足够的空间，这样就成功的实现了单侧投影。

完整的代码也很简单：

```HTML
<div class="g-overflow"></div>
```
```CSS
.g-overflow {
    position: relative;
    width: 200px;
    height: 300px;
    overflow: hidden;
    
    &:before {
        content: "";
        position: absolute;
        inset: 0 0 100px;
        border: 1px solid #000;
        box-shadow: 0 0 6px 2px;
    }
}
```

效果如下：

![](https://github.com/chokcoco/iCSS/assets/8554143/771d0b33-6eee-440f-bda2-efc8b434b74d)
