### ISSUE TITLE
【现代 CSS】更强大的 :nth-child 选择器 

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#267]
今天群里讨论了一个非常有意思与 CSS 选择器相关的题目。题目如下：

假设我们如下的 HTML 结构：

```HTML
<div class="box">
    <p class="aa">aaaaaaaaaaaa</p>
    <p class="bb">bbbbbbbbbbbb</p>
    <p class="cc">cccccccccccc</p>
    <p class="aa">aaaaaaaaaaaa</p>
    <p class="bb">bbbbbbbbbbbb</p>
    <p class="cc">cccccccccccc</p>
    <p class="aa">aaaaaaaaaaaa</p>
    <p class="bb">bbbbbbbbbbbb</p>
    <p class="cc">cccccccccccc</p>
</div>
```

效果如下：

![](https://github.com/chokcoco/iCSS/assets/8554143/b43ef610-a3fd-4f4e-ac40-da352fbaf007)

**如何在不添加类名的情况下，快速的选取第一个 class 为 `.cc` 的元素**？

当然，上面的结构示意图只是一种可能的情况，这里想表述的场景的意思是：

1. 我们希望选取的 `.cc` 元素，在其父元素下，存在多个 `.cc`，**所以需要精准定位第一个**；
2. `.cc` 元素**一定不是其所有兄弟元素中的第一个**；
3. 不允许使用类似 `.bb + .cc` 的方式直接进行选取，因为第一个 `.cc` 元素的上一个元素不一定是 `.bb`，可以是其他任何元素；

基于上述的限定条件，你可以暂停阅读，思考 20 秒，可能的方式有哪些？

## 使用 :nth-child 或者 :nth-of-type

一般而言，比较容易想到的，肯定是首先使用 `:nth-child` 和 `:nth-of-type` 伪类选择器进行尝试。

但是，遗憾的是，这两个选择器都无法做到在上述结构下，成功选取第一个 `.cc` 元素。

代码如下：

```CSS
.box .cc:nth-child(1) {
    color: red;
    font-size: 24px;
}
```

或者

```CSS
.box .cc:nth-of-type(1) {
    color: red;.box .cc:nth-child(1) {
    color: red;
    font-size: 24px;
}
```

也就是说，上述两种方式，都是不行的。简单解释一下：

1. 对于 `:nth-child` 而言，`:nth-child()` [伪类](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Pseudo-classes)根据元素在父元素的子元素列表中的索引来选择元素。最为核心的是，选择器，它是**根据父元素内的所有兄弟元素的位置来选择子元素**。

这里最重要的是，它是**根据父元素内的所有兄弟元素的位置来选择子元素**，而我们无法得知在实际业务场景下，第一个 `.cc` 到底处于第几个索引。因此，这个选择器明显没法胜任。

2. 对于 `:nth-of-type` 而言，**基于相同类型（标签名称）的兄弟元素中的位置来匹配元素**。

非常重要的一点是，**使用此选择器无法选择基于相同类名的元素的位置，来匹配元素**。

什么意思呢？

如果我们把上述 DEMO 改造，改造成这样：

```HTML
<div class="box">
    <p class="aa">aaaaaaaaaaaa</p>
    <span class="bb">bbbbbbbbbbbb</span>
    <div class="cc">cccccccccccc</div>
    <p class="aa">aaaaaaaaaaaa</p>
    <span class="bb">bbbbbbbbbbbb</span>
    <div class="cc">cccccccccccc</div>
    <p class="aa">aaaaaaaaaaaa</p>
    <span class="bb">bbbbbbbbbbbb</span>
    <div class="cc">cccccccccccc</div>
</div>
```

再基于上述结构下，选择第一个 class 为 `.cc` 的元素，就可以利用 `:nth-of-type` 实现：

```CSS
.box div:nth-of-type(1) {
    color: red;
    font-size: 24px;
}
```

效果如下：

![](https://github.com/chokcoco/iCSS/assets/8554143/d128628b-bae0-42d1-a69e-fd04d020c29d)
