### ISSUE TITLE
谈谈一些有趣的CSS题目（1）-- 左边框的多种实现方式

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#51]
开本 `issues` ，讨论一些有趣的 CSS 题目，抛开实用性而言，一些题目为了拓宽一下解决问题的思路，此外，涉及一些容易忽视的 CSS 细节。

解题不考虑兼容性，题目天马行空，想到什么说什么，如果解题中有你感觉到生僻的 CSS 属性，赶紧去补习一下吧。

不断更新，不断更新，不断更新，重要的事情说三遍。
## 1、下面这个图形，只使用一个标签，可以有多少种实现方式：

![border](http://images.cnblogs.com/cnblogs_com/coco1s/881614/o_border.png)

假设我们的单标签是一个 `div`:

``` html
<div></div>
```

定义如下通用`CSS`：

``` css
div{
    position:relative;
    width:200px;
    height:60px;
    background:#ddd;
}
```
### 法一：border

这个应该是最最最容易想到的了

``` css
div{
    border-left:5px solid deeppink;
}
```
### 法二：使用伪元素

一个标签，算上 `before` 与 `after` 伪元素，其实算是有三个标签，这也是很多单标签作图的基础，本题中，使用伪元素可以轻易完成。

``` css
div::after{
    content:"";
    width:5px;
    height:60px;
    position:absolute;
    top:0;
    left:0;
    background:deeppink;
}
```
### 法三：外 box-shadow

盒阴影 `box-shadow` 大部分人都只是用了生成阴影，其实阴影可以有多重阴影，阴影不可以不虚化，这就需要去了解一下 `box-shaodw` 的每一个参数具体作用。使用 `box-shaodw` 解题：

``` css
div{
    box-shadow:-5px 0px 0 0 deeppink;
}
```
### 法四：内 box-shadow

盒阴影还有一个参数 `inset` ，用于设置内阴影，也可以完成：

``` css
div{
    box-shadow:inset 5px 0px 0 0 deeppink;
}
```
### 法五：drop-shadow

`drop-shadow` 是 CSS3 新增滤镜 `filter` 中的其中一个滤镜，也可以生成阴影，不过它的数值参数个数只有 3 个，比之 box-shadow 少一个。

``` css
div{
    filter:drop-shadow(-5px 0 0 deeppink);
}
```
### 法六：渐变 linearGradient

灵活使用 CSS3 的渐变可以完成大量想不到的图形，CSS3 的渐变分为线性渐变和径向渐变，本题使用线性渐变，可以轻易解题：

``` css
div{
    background-image:linear-gradient(90deg, deeppink 0px, deeppink 5px, transparent 5px);
}
```
### 法七：轮廓 outline

这个用的比较少，outline （轮廓）是绘制于元素周围的一条线，位于边框边缘的外围，可起到突出元素的作用。这个方法算是下下之选。

``` css
div{
    height:50px;
    outline:5px solid deeppink;
}
div{
    position:absolute;
    content:"";
    top:-5px;
    bottom:-5px;
    right:-5px;
    left:0;
    background:#ddd;
}
```
### 法八: 滚动条

这个方法由 [小火柴的蓝色理想](http://www.cnblogs.com/xiaohuochai/) 提供，通过改变滚动条样式实现：

``` CSS
div{
    width:205px;
    background:deeppink;
    overflow-y:scroll;
}
div::-webkit-scrollbar{
    width: 200px;
    background-color:#ddd;
}
```

抛开实用性，仅仅是模拟出这个样式的话，这个方法真的让人眼前一亮。

上述就是想到的 8 种方法，不排除有没想到的，希望有其他的方法可以在评论中提出，具体 8 种实现可以戳这里看看：

[codepen-单标签左边竖条的实现方式  ](https://codepen.io/Chokcoco/pen/PGkgRX)

**Comment by nonbeingLi** [comment]
轮廓 outline的方法尝试后行不通

**Comment by chokcoco** [comment]
@nonbeingLi 嗯。这里需要一个伪元素帮助遮挡一下~

**Comment by leitongda** [comment]
伪元素 :first-letter  加上 特殊字符 ▎ 也可以实现

**Comment by NSGUF** [comment]
> 轮廓 outline的方法尝试后行不通 应该是需要两个div嵌套吧

div加上position:relative就行了

**Comment by arzyu** [comment]
开个脑洞，:p

```css
{
    display: list-item;
    list-style: square inside;
    width: 200px;
    height: 40px;
    padding-left: 5px;
    line-height: 0;
    font-size: 9999%;
    overflow: hidden;
    background: deeppink;
    color: #ddd;
}
```
