### ISSUE TITLE
探究 flex 盒子下 margin 的更多用法

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#64]
为了引出本文的主题，先看看这个问题，最快垂直居中一个元素的方法是什么？

垂直居中也算是 CSS 领域最为常见的一个问题了，不同场景垂直居中的方法也各不相同。嗯，下面这种应该算是最便捷的了：

```HTML
<div class="g-container">
    <div class="g-box"></div>
</div>
```

```CSS
.g-container {
    display: flex;
}

.g-box {
    margin: auto;
}
```
> 当然，上面的 `display: flex` 替换成 `display: grid` 也是可以的。
