### ISSUE TITLE
CSS 技巧一则：height 过渡动画

### ISSUE THREAD

**Issue by chokcoco** [chokcoco/iCSS#91]
本文未完成
----

这个问题源自于掘金上的一个留言，一个朋友问到，为什么我下面这段代码的高度过渡动画失效了？

伪代码大概是这样：

```CSS
{
    height: unset;
    transition: all 0.3s linear;
    will-change: height;

    &.up {
        height: 0;
    }
    &.down {
        height: unset;
    }
}
```

把它还原成一个实际的 Demo，效果大概是这样：

![heightransition1](https://user-images.githubusercontent.com/8554143/104202487-f3952500-5465-11eb-9571-0fe0249d9ceb.gif)

嗯哼？很奇怪，明明给 `height` 属性设置了 `transition`，为什么过渡动画没有触发，而是直接一步到位展开了呢？

我们期待的效果是这样的：

![heightransition2](https://user-images.githubusercontent.com/8554143/104203001-98176700-5466-11eb-9aaa-57c5f6603003.gif)

## transition 不支持 height: auto

当上述代码设置成 `height: unset` 时，实际等同于设置了 `height: auto`，我们的想法是希望这段代码能够容器支持文本的动态高度。每次展开的时候，过渡展开到容器本身的高度即可。

查看规范，究其原因，在于 **CSS transtion 不支持元素的高度为 auto 的变化**。

如果把上述的 `height: unset` 替换成一个具体的高度值，则动画是生效的，譬如：

```CSS
{
    &.up {
        height: 0;
    }
    &.down {
      - height: unset;
      + height: 500px;
    }
}
```

![heightransition3](https://user-images.githubusercontent.com/8554143/104203841-8edaca00-5467-11eb-8766-3ffc1a619d40.gif)

但是，我们又希望能够做到动态高度的过渡转换，是不是就没有办法了么？

## 巧用 `max-height` 适配动态高度

嘿嘿，这里有一个非常有意思的小技巧。既然不支持 `height: auto`，那我们就另辟蹊径，利用 `max-height` 的特性来做到动态高度的伸缩。

我们改造一下上述代码，将 `height: 0` 替换为 `max-height: 0`，将 `height: auto` 替换成 `max-height: 1000px`，伪代码大概是这个意思：

```CSS
{
    max-height: 0;
    transition: max-height 0.3s linear;

    &.up {
        max-height: 0;
    }
    &.down {
        max-height: 1000px;
    }
}
```

我们估算一下实际容器的最大高度，这里的 `1000px` 只需要比最大高度高即可。

由于 `max-height` 只是限制文本的最大高度，当容器的实际高度没有达到限制的最大高度，将不会继续变高，看看效果：

![heightransition4](https://user-images.githubusercontent.com/8554143/104206251-4375eb00-546a-11eb-87a9-21a312e0e707.gif)

[CodePen Demo -- the height property transition unwork](https://codepen.io/Chokcoco/pen/YzGOjqQ)
